### ISSUE TITLE
Проксирование traefik'ом по портам 3306 и 5432

### ISSUE THREAD

**Issue by dmitrystetyukha** [local-deploy/dl#123]
Поможет обладателям компов на шындоуз с wsl
Что может исправить: 
Сейчас при попытке подключиться к контейнеру с бд по айпи из `dl ps` запущенному в wsl, не получается
Даже если сделать мирроринг сетей между хостом и wsl, можно лишь из wsl получить доступ к сетям на хосте, а не наоборот

**Comment by varrcan** [comment]
Добрый день, к сожалению, через traefik так сделать нельзя.. Я уже думал в эту сторону
https://github.com/traefik/traefik/issues/5155

**Comment by dmitrystetyukha** [comment]
очень жаль, пойду накатывать ubuntu :(
