### ISSUE TITLE
Проблемы совместимости с trafick v3.0

### ISSUE THREAD

**Issue by Gasparonik** [local-deploy/dl#129]
у nginx контейнера описание такое: 

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${NETWORK_NAME}.entrypoints=web"
      - "traefik.http.routers.${NETWORK_NAME}.rule=Host(`${HOST_NAME}.localhost`) || HostRegexp(`{subdomain:.*}.${HOST_NAME}.localhost`) || HostRegexp(`${HOST_NAME}.{ip:.*}.nip.io`) || HostRegexp(`{subdomain:.*}.${HOST_NAME}.{ip:.*}.nip.io`)"
      - "traefik.http.routers.${NETWORK_NAME}_ssl.entrypoints=websecure"
      - "traefik.http.routers.${NETWORK_NAME}_ssl.rule=Host(`${HOST_NAME}.localhost`) || HostRegexp(`{subdomain:.*}.${HOST_NAME}.localhost`) || HostRegexp(`${HOST_NAME}.{ip:.*}.nip.io`) || HostRegexp(`{subdomain:.*}.${HOST_NAME}.{ip:.*}.nip.io`)"
      - "traefik.http.routers.${NETWORK_NAME}_ssl.tls=true"
      - "traefik.docker.network=dl_default"
      
      
 домен localhost работает, а nip.io отдает 404 ошибку.
 
 
 Заметил, что недавно вышла новая версия traefick 3.0
 
 Вы же устанавливаете последнюю версию всегда, как я понял: 
 
![image](https://github.com/local-deploy/dl/assets/58563793/f40f1486-c681-4ad7-9966-efff95613398)

 
Нам помогло "обмануть" с помощью команд

docker image rm trafick
docker pull traefik:v2.10.7
docker tag traefik:v2.10.7 traefik:latest
 
 Предлагаемое решение проблемы: временно зафиксировать версию 2
 
 Иначе, как мне кажется, придется переписывать конфиги всех проектов в docker-compose.yml

**Comment by varrcan** [comment]
Добрый день! Спасибо, что указали на ошибку. Да, в версии 3.0 разработчики сломали регулярки параметра `HostRegexp`, он теперь работает по синтаксису Go.
Я временно залочил версию Traefik на 2.10.7, как быстрое решение.

**Comment by varrcan** [comment]
Исправления в версии [1.1.1](https://github.com/local-deploy/dl/releases/tag/1.1.1)
