### ISSUE TITLE
[BUG] Не работает команда из 

### ISSUE THREAD

**Issue by onilopic** [local-deploy/dl#132]
### Description

В документации сказано что команда запустит один сервис?

```bash
dl service up -s portainer
````

Выдаёт ошибку: 

`Error: unknown shorthand flag: 's' in -s`

Тоже самое с `dl service down`

### DL version

```Text
1.1.1
```

### Operating system

```Text
Ubuntu 24.4
```

**Comment by varrcan** [comment]
Здравствуйте! Документация, как обычно, страдает и обновляется в последнюю очередь..
Не так давно в корне изменился Docker API, который используется для запуска контейнеров этих трёх сервисов. После рефакторинга применить к функционалу параметры запуска одного сервиса стало проблематично, поэтому они были удалены.

Если для вас этот параметр важен, я попробую восстановить функционал. Либо приведу в порядок документацию.
Как сильно востребован для вас этот функционал?

**Comment by onilopic** [comment]
Здравствуйте, не кретичен. Можно через docker выключить не нужные контейнеры. Вопрос удобства.

**Comment by varrcan** [comment]
Восстановлено в версии [1.1.2](https://github.com/local-deploy/dl/releases/tag/1.1.2)

Теперь можно передать параметром не один контейнер, а несколько (через запятую).
Также дополнительно реализован функционал отключения запуска контейнеров portainer и mail (mailcatcher) по команде 
`dl config service`

Документация обновлена
