### ISSUE TITLE
редирект на статику

### ISSUE THREAD

**Issue by evgeny-xpage** [local-deploy/dl#20]
Часто в проектах ссылка на ститические файлы, например в каталоге, имеет формат /upload/..., было бы отлично добавить конфиг в .env, в который указать домен для статических файлов, которые отсутствуют физически на локальной машине.

**Comment by varrcan** [comment]
Статику из upload можно проксировать с production сервера, например, через apache, для этого в файле .htaccess нужно прописать примерно такой код, после объявления RewriteEngine On:

```
RewriteCond %{ENV:ENVIRONMENT} ^dl$
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_URI} \.(gif|jpe?g|png|ico|svg|webp)$
RewriteRule ^(.*)$ https://www.site.ru/$1 [R,NC,L]
```

Замените домен в последней строке на свой. 

Это правило будет отрабатывать только на локальном проекте, в первой строке стоит условие на env-переменную со значением `dl`, которую устанавливает утилита. То есть код можно закоммитить.

Быть может это решит вашу проблему?

**Comment by evgeny-xpage** [comment]
За решение спасибо. Речь шла именно о том, чтобы добавить эту возможность "из коробки", вынести в конфиг https://www.site.ru/

**Comment by varrcan** [comment]
К сожалению, для apache не получится так сделать, только через .htaccess файл. Но если запустить проект через php-fpm, там это доступно из коробки на уровне nginx, если в переменной HOST_NAME, в .env файле, указан домен production-сайта 
![img220920228112](https://user-images.githubusercontent.com/23196073/191823258-e024ce19-85c8-49a9-9f37-00ab24616d4f.png)
