### ISSUE TITLE
Вопрос по Redis

### ISSUE THREAD

**Issue by evgeny-xpage** [local-deploy/dl#24]
Скачал локально битриксовый проект, который очень зависим от редиса. 
в .env добавлен REDIS=true
Но имеем ошибку
```
[Error] 
Class 'Redis' not found (0)
```
Подскажите пожалуйста как следует себя вести в проектах с редисом, Нужно залесть в контейнер через dl bash -r и установить php-redis или каким-то иначе?

**Comment by varrcan** [comment]
В документации не добавлена переменная, которая позволяет активировать некоторые модули php. По умолчанию подключается только дополнительный модуль opcache

Нужно в .env файл добавить:
`PHP_MODULES="opcache redis"`

После пеерзапуска контейнера php появится Redis


![img1409202281cc](https://user-images.githubusercontent.com/23196073/190095724-dc6730cd-7a41-4d30-9a67-dc9e5159b4d7.png)

**Comment by varrcan** [comment]
Обновил документацию, спасибо
https://local-deploy.github.io/ru/getting-started/env#%D0%BD%D0%B0%D1%81%D1%82%D1%80%D0%BE%D0%B9%D0%BA%D0%B8-php
