### ISSUE TITLE
"dl deploy" question

### ISSUE THREAD

**Issue by evgeny-xpage** [local-deploy/dl#30]
![image](https://user-images.githubusercontent.com/74767371/190973999-de97243c-c539-4001-a5aa-ef93bd71e7c4.png)

На компе у коллеги пытались развернуть первый проект.вылетел с такой ошибкой. Можете подсказать в какую сторону думать?

**Comment by varrcan** [comment]
Проверьте, запустился ли контейнер с базой. Можно в портейнере http://portainer.localhost/ или через команду docker ps. Посмотреть логи контейнера, это также можно сделать через портейнер.

**Comment by varrcan** [comment]
Напишите мне в чат, если не сможете найти причину ошибки https://t.me/localdeploy

**Comment by evgeny-xpage** [comment]
вернулись к этому вопросу.  
прошел в portainer и увидел, что он не запущен впринципе.

попробовал dl service up, но картина не поменялась
сделал dl service up -r, и он ожил.
После этого все заработало.

Спасибо за оперативный ответ

**Comment by varrcan** [comment]
Не обычное поведение, конечно. Дайте знать, пожалуйста, если баг повторится. Попробуем разобраться, почему так происходит.
