### ISSUE TITLE
Нашел важную проблему

### ISSUE THREAD

**Issue by evgeny-xpage** [local-deploy/dl#43]
Неоднократно возникали случайные проблемы на разных компах у разных людей. Оказывается если проект размещен по пути, в котором встречается кириллица, то будут проблемы. При чём часто случайны.
например если закинуть ~/Рабочий стол/projects/veryValuableProject то шанс 146%, что не будет работать dl deploy

**Comment by varrcan** [comment]
Спасибо за обратную связь, посмотрю, что можно сделать

**Comment by varrcan** [comment]
Похоже проблема не в кириллице, а в пробеле в имени директории. И не с утилитой DL, а с командой декомпрессии архива gunzip. 
Я создал для примера путь, который вы указали, ошибка произошла в момент распаковки базы данных, команда gunzip выдала ошибку `~/Рабочий: Нет такого файла или каталога`, то есть пробел не распознала.

При передаче пути нужно использовать обратный слеш перед пробелом, например, `~/Рабочий\ стол/`, но в Golang нет никакой нативной функции для подобного экранирования. По умолчанию, Go и так корректно работает с пробелами, ему это не нужно.

Как вариант, можно попробовать использовать относительный путь. Я поправил код, у меня локально работает корректно. Не могли бы вы протестировать у себя?

Во вложении архив с файлом dl, его нужно распаковать, потом поместить файл dl в директорию ~/.local/bin и установить права на выполнение.

```bash
wget https://github.com/local-deploy/dl/files/9795422/dl.zip
unzip dl.zip && rm dl.zip
mv dl ~/.local/bin/dl && chmod +x ~/.local/bin/dl
```

[dl.zip](https://github.com/local-deploy/dl/files/9795422/dl.zip)
