### ISSUE TITLE
Вебсокеты

### ISSUE THREAD

**Issue by jasmanchik** [local-deploy/dl#51]
На некоторых проектах в работе используются веб-сокеты. Не хватает возможности настраивать и запускать их локально. Будет круто, если эта возможность появится

**Comment by varrcan** [comment]
Кажется я не понимаю, о чем речь. Вебсокеты это не про локальный деплой проекта, это функционал уровня приложения.
Вы хотите, чтобы локально запускался какой то демон и держал коннект с клиентом?
Существует десятки способов реализации, и кажется, что это все таки должен реализовать разработчик, учитывая логику и потребности проекта.

**Comment by jasmanchik** [comment]
Да вы верно понимаете, но требуется настройка конфигов nginx и открытие определенных портов для работы. Например где располагается кфг nginx я не нашел(

**Comment by varrcan** [comment]
В nginx там пару строк нужно прописать, а порты это только на уровне контейнера. Теперь понял вас, посмотрю, что можно сделать.

**Comment by Tickfl** [comment]
В конфигурации .env появилась переменная NGINX_CONF, она работает только при использовании php-fpm?

**Comment by Tickfl** [comment]
В конфигурации .env появилась переменная NGINX_CONF, она работает только при при использовании php-fpm?

**Comment by varrcan** [comment]
> В конфигурации .env появилась переменная NGINX_CONF, она работает только при при использовании php-fpm?

Да, верно. Если используется образ php-fpm, дополнительно поднимается контейнер nginx со стандартным конфигом, который вы можете переопределить. 
Сам конфиг расположен по пути: ~/.config/dl/config-files/default.conf.template
Вы можете скопировать его в директорию проекта, настроить и подключить через NGINX_CONF.

Например: `NGINX_CONF=.docker/nginx.conf.template`

**Comment by varrcan** [comment]
В версии [0.5.7](https://github.com/local-deploy/dl/releases/tag/0.5.7) добавлены незащищённые веб-сокеты на порту 8081

Пример использования https://github.com/local-deploy/dl-example/tree/master/websocket
