### ISSUE TITLE
Ошибка после обновления

### ISSUE THREAD

**Issue by jasmanchik** [local-deploy/dl#53]
Сейчас обновился до версии 0.5.2, и вот такая пасхалка прилетела при запуске проекта. Посмотрите?)
<img width="1109" alt="Снимок экрана 2022-12-08 в 19 26 06" src="https://user-images.githubusercontent.com/40543800/206435861-f209ff21-2923-4161-9951-3ca2ed6046c1.png">
ОС: Mac

**Comment by varrcan** [comment]
Какая красота.. А можете запустить с параметром дебага?
`dl up --debug`

**Comment by jasmanchik** [comment]
Контейнеры работали весь день, все было хорошо. Вечером обновился и не запускаются
<img width="1081" alt="Снимок экрана 2022-12-08 в 19 38 26" src="https://user-images.githubusercontent.com/40543800/206437714-1da791c2-1cac-4078-8171-627ac28932e0.png">

**Comment by varrcan** [comment]
Можете в телегу написать? Быстрее будет
https://t.me/localdeploy
