### ISSUE TITLE
Передача параметров через -- при exec

### ISSUE THREAD

**Issue by MrDeff** [local-deploy/dl#55]
Пример
`dl exec php artisan make:migration add_json_field_to_query_result --table=query_data
`

в ответ получим
`
Error: unknown flag: --table
Usage:
  dl exec [command] [flags]

Examples:
dl exec composer install
dl exec "ls -la"

Flags:
  -h, --help   help for exec

Global Flags:
      --debug   Show more output

Error: unknown flag: --table
`

а должны передать эти параметры в контейнер

**Comment by varrcan** [comment]
Да, с этим есть косяк. Сам dl пытается перехватить параметры. Нужно доработать команду.
Взлетит, только если передать команду в кавычках. 
`dl exec "bash -c \"php artisan make:migration add_json_field_to_query_result --table=query_data\""`

**Comment by varrcan** [comment]
Есть решение проще, можно не вызывать команду через bash -c, а просто передать её в кавычках:
`dl exec "php artisan make:migration add_json_field_to_query_result --table=query_data"`
Так тоже сработает, главное, чтобы вызываемая команда находилась в PATH.

Без кавычек не получается никак, разве что указать конкретные аргументы, которые не должны перехватываться. Я просто не смогу разрулить, относится аргумент к dl или его нужно передать в контейнер.
