### ISSUE TITLE
Error: Process exited with status 2

### ISSUE THREAD

**Issue by evgeny-xpage** [local-deploy/dl#61]
![dl_error](https://user-images.githubusercontent.com/74767371/214040520-4d13262b-b02b-48ac-b375-6248e6e09396.png)
Происходит ошибка с конкретным проектом. Есть ли понимание на что следует обратить внимание? Другие проекты вроде нормально качаются.

**Comment by varrcan** [comment]
Попробуйте запустить деплой в режиме отладки: `dl deploy --debug`

**Comment by evgeny-xpage** [comment]
![image](https://user-images.githubusercontent.com/74767371/214045486-92c67926-1f24-4c41-b270-31b28e96a811.png)
висит так уже долго. минут 5, хотя там понты совсем

**Comment by varrcan** [comment]
> висит так уже долго. минут 5, хотя там понты совсем

вот прямо сейчас на сервере должен лежать архив production.tar.gz, вы можете скачать его вручную и посмотреть содержимое, все ли корректно запаковано?

ps простите, отредактировал ваш скриншот, затер информацию, которую лучше не светить

**Comment by evgeny-xpage** [comment]
как ни странно оно провисело минут 10 или 15. и скачалось.
![image](https://user-images.githubusercontent.com/74767371/214046933-b8c9ce61-ea9e-435e-9d3d-689c2aeaf43a.png)

**Comment by evgeny-xpage** [comment]
возможно помехи со стороны сервера и он обрывал соединение по каким-то причинам. сейчас не обрывает.
