### ISSUE TITLE
возможности исключений таблиц.

### ISSUE THREAD

**Issue by evgeny-xpage** [local-deploy/dl#62]
есть ли возможность исключать таблицы таким образом, чтобы схема переносилась, а данные - нет? Есть ряд проектов где существование таблиц необходимо, но они слишком тяжелые и dl deploy длится часы

**Comment by varrcan** [comment]
Сейчас так и работает, сначала выполняется дамп только структуры, потом дамп данных с исключением таблиц

![img300120232956](https://user-images.githubusercontent.com/23196073/215455900-c8947eb4-328a-4ded-b593-881a4c3178af.png)

Исключаемые таблицы указываются в env-параметре EXCLUDED_TABLES (список таблиц в виде строки, разделенными запятой)

**Comment by evgeny-xpage** [comment]
получается я сам додумал, что это не продумано. Приношу извинения. Проверим ,спасибо.
