### ISSUE TITLE
imagick

### ISSUE THREAD

**Issue by evgeny-xpage** [local-deploy/dl#63]
Подскажите как быть с imagick расширением.

PHP_MODULES="imagick" в .env файле приводит к тому, что контейнер стартует не корректно и по адресу открывается 404
Есть ли корректный способ включения?

**Comment by varrcan** [comment]
Скорее всего контейнер не стартует просто из-за ошибки, так как этого пакета нет в образе. 
ImageMagick специфичная утилита, никогда особо и не требовалась, на самом деле (может быть исторически так сложилось). Даже на большинстве хостингов стоит только GD, возможно потому, что он ограничен памятью PHP, в то же время у ImageMagick такого ограничения нет, насколько я помню.
Тут еще момент, что пакет потянет за собой много зависимостей, что плохо скажется на размере образа, он и так не маленький сейчас. Только основные зависмости потянут где-то на 80Мб (при текущем весе образа php примерно 650Мб, это не мало)

Вы считаете ImageMagick остро необходим в образе?

**Comment by evgeny-xpage** [comment]
ситуация такая. есть замечательный проект geometria.ru в котором очень очень много фото. Нужно было найти баланс между качеством и весом для чего перепробовали наверное все библиотеки что существуют и остановились на конкретно конфигурации imagick. Вместе с тем понятно, что ситуация разовая. Видимо придется делать это вручную.

**Comment by evgeny-xpage** [comment]
> Скорее всего контейнер не стартует просто из-за ошибки, так как этого пакета нет в образе. ImageMagick специфичная утилита, никогда особо и не требовалась, на самом деле (может быть исторически так сложилось). Даже на большинстве хостингов стоит только GD, возможно потому, что он ограничен памятью PHP, в то же время у ImageMagick такого ограничения нет, насколько я помню. Тут еще момент, что пакет потянет за собой много зависимостей, что плохо скажется на размере образа, он и так не маленький сейчас. Только основные зависмости потянут где-то на 80Мб (при текущем весе образа php примерно 650Мб, это не мало)
> 
> Вы считаете ImageMagick остро необходим в образе?

По поводу GD. он отказывается работать с webp (Call to undefined function imagewebp) и требует специальной конфигурации. Есть ли возможность сделать это через .env?

**Comment by varrcan** [comment]
да, действительно, gd собран без webp. через env не получится, но можно попробовать пересобрать образ, указав этот модуль. 
вы какую версию php используете? я могу для теста попробовать указать сначала в одном, потом можно будет распространить на другие образы

**Comment by evgeny-xpage** [comment]
8.1

**Comment by varrcan** [comment]
> 8.1-apache

укажите в .env файле переменную:
`PHP_IMAGE_VERSION=1.0.3`
и поднимите проект. 

PS Процесс скачивания контейнера может отображаться неправильно, это недокументированная переменная

**Comment by evgeny-xpage** [comment]
работает. можно ожидать что с новой версией это станет доступно? например на 7.4

**Comment by varrcan** [comment]
> работает. можно ожидать что с новой версией это станет доступно? например на 7.4

Вы можете использовать этот образ, он меняться не будет, я просто пропишу его в самом dl по умолчанию (чтобы не указывать тег через PHP_IMAGE_VERSION). 
Как добавлю модуль webp в другие образы, сделаю релиз, конечно.  Думаю до завтра справлюсь )

**Comment by varrcan** [comment]
Все же тег будет другой, я еще composer до последнего обновил.

https://github.com/local-deploy/dl/releases/tag/0.5.5
