### ISSUE TITLE
Механизм замены php.ini в контейнере

### ISSUE THREAD

**Issue by VlMescher** [local-deploy/dl#67]
![image](https://user-images.githubusercontent.com/129059800/230274914-c2cd6271-e095-47de-aa15-17295b8c70b9.png)
по умолчанию включен вывод ошибок. Можно ли его вырубить через конфиг файл? Может стоит его убрать из сборки?

**Comment by varrcan** [comment]
Опция всегда включена и я не предусматривал её отключение через конфиг. Но ведь для локальной разработки крайне важно видеть возможные ошибки.
Можете рассказать, почему вы не хотите видеть ошибки интерпретатора в процессе разработки?

**Comment by VlMescher** [comment]
не мало причин. например в админке битриксовой стандартные запросы на бэк получают иногда не ожидаемый ответ, а с содержанием текста какого-нибудь warning. При инсталяции дистрибутива весь экран усеян предупреждениями.

**Comment by VlMescher** [comment]
Как побороть ошибки вручную это ясно, это не прям проблема, я лишь хотел уточнить нужен ли этот вывод ошибок. Если вы считаете, что он полезен, тогда конечно логичнее его оставить.

**Comment by varrcan** [comment]
Рекомендуется включать вывод ошибок на dev проектах. Это даже не моё личное мнение. Как пример, вот php.ini для разработки из официального репозитория:
https://github.com/php/php-src/blob/master/php.ini-development#L516

```
error_reporting = E_ALL
display_errors = On
display_startup_errors = On
```

Но ваша просьба вполне логична, некоторые параметры в php.ini действительно должны переопределяться. Возможно стоит рассмотреть механизм замены php.ini в контейнере через монтирование локального файла. Прописывать каждую переменную в конфиг будет нерационально. Добавлю такую возможность в беклог.

**Comment by varrcan** [comment]
Реализовано в версии [1.1.0](https://github.com/local-deploy/dl/releases/tag/1.1.0)
Теперь можно переопределить любую переменную в php.ini

В env файл нужно указать:
`PHP_INI_SOURCE=.docker/php.ini`

где `.docker/php.ini` - относительный путь к конфигу

![img260120249edd](https://github.com/local-deploy/dl/assets/23196073/e3ddd44f-ad19-4f5b-b9dd-ecb5e64cbc26)
