### ISSUE TITLE
HTTP 2

### ISSUE THREAD

**Issue by morvit** [local-deploy/dl#69]
Можно ли что-то придумать HTTP 2?
Очень хотелось бы прорабатывать на локальное машине вещи вида EventSource (Web Api)...

**Comment by varrcan** [comment]
HTTP/2 может работать только с валидными SSL сертификатами. Это очень усложняет задачу, так как получить сертификат для локального сайта невозможно.

Есть обходной путь - это добавить кастомный сертификат в доверенные браузера. Но для этого нужен как минимум root доступ, чтобы установить сторонние пакеты.

Как пример https://github.com/FiloSottile/mkcert

Не уверен, что получится это реализовать "под капотом" и не уверен, что это действительно нужно.. Но в теории, это должно работать. Могу попробовать написать отдельную инструкцию.

**Comment by morvit** [comment]
А что, если, например добавить конфигурационную переменную PUBLIC_HOST_NAME (предполагается наличие статического белого IP-адреса у ПК разработчика), в ней задаем реальное доменное имя – site.example.online (у доменного имени прописываем A-запись ПК). При ее наличии в traefik добавляем соответствующее правило и добавляем какой-нибудь образ letsencrypt?

ЗЫ: Конечно не повседневная задача, но наличие такой возможности было бы пушкой.

**Comment by Tickfl** [comment]
> HTTP/2 может работать только с валидными SSL сертификатами. Это очень усложняет задачу, так как получить сертификат для локального сайта невозможно.
> 
> Есть обходной путь - это добавить кастомный сертификат в доверенные браузера. Но для этого нужен как минимум root доступ, чтобы установить сторонние пакеты.
> 
> Как пример https://github.com/FiloSottile/mkcert
> 
> Не уверен, что получится это реализовать "под капотом" и не уверен, что это действительно нужно.. Но в теории, это должно работать. Могу попробовать написать отдельную инструкцию.

Если напишите инструкцию - будет супер)

**Comment by varrcan** [comment]
Ок, попробую у себя это все проделать сначала, вдруг не взлетит )

**Comment by VlMescher** [comment]
может самоподписанные сертификаты можно через traefik использовтаь

**Comment by varrcan** [comment]
Пока что в тестовом режиме и только для Linux (mac в теории тоже должен работать, но еще не проверял). 

1. [Обновитесь](https://local-deploy.github.io/ru/getting-started/install) на последнюю версию 1.0.3
2. Установите пакет `sudo apt install libnss3-tools`
3. Запустите команду генерации и установки в браузер корневого самоподписанного сертификата: `dl cert install`. Это нужно сделать один раз. Работает с Firefox и Chrome (Opera, Yandex)
4. Дальше запускаете проект как обычно, `dl up`. 

Сертификат для проекта будет сгенерирован автоматически при старте и прочитан traefik. После остановки проекта через `dl down`, сертификат также удаляется (чтобы не висел мертвым грузом).
