### ISSUE TITLE
mysqldump

### ISSUE THREAD

**Issue by VlMescher** [local-deploy/dl#70]
Добрый день. На некоторых гигантских проектах с большой бд иногда требуется обновить конкретню таблицу с прода.

хотелось бы иметь возможность примерно следующего функционала (пример воображаемой команды):
~dl mysqldump b_user, b_iblock_section

**Comment by varrcan** [comment]
Здравствуйте! Думаю, такая опция может быть полезной, добавить её к команде deploy, по аналогии с директориями, что-то типа:

```
dl deploy --database --tables b_user,b_iblock_section
dl deploy -d -t b_user,b_iblock_section
```

Добавил в бэклог

**Comment by varrcan** [comment]
Реализовано в версии 1.0.1
