### ISSUE TITLE
проблема с конфигом

### ISSUE THREAD

**Issue by VlMescher** [local-deploy/dl#71]
оказывается если в перечислении в EXCLUDED_FILES= допустить пробел, например в моём случае перед bitrix/backup, то dl deploy будет падать с ошибкой. При чём ошибка слабо информативно даже с флагом --debug пишет  exiting with status 2.

Зашел на сервер и руками повторил команду которая выводилась в debug. - получил более подробную ошибку, что папки bitrix/backup не существует.

**Comment by varrcan** [comment]
Уточните, пожалуйста, имеется ввиду после знака равно в переменной, или после запятой?
`EXCLUDED_FILES=bitrix/tmp, bitrix/backup`
`EXCLUDED_FILES= bitrix/tmp,bitrix/backup`

**Comment by VlMescher** [comment]
еще вспомнил забавный случай. Однажды рандомный пароль от mysql содержал #. Вставлял вслепую и не обратил внимание, что это ломает конфиг) завернул в кавычки

**Comment by varrcan** [comment]
Понял, спасибо, лишний пробел после запятой. Нужно тримить значения.

**Comment by VlMescher** [comment]
> > еще вспомнил забавный случай. Однажды рандомный пароль от mysql содержал #. Вставлял вслепую и не обратил внимание, что это ломает конфиг) завернул в кавычки
> 
> Такой уж синтаксис env файлов, знак # ставит комментарий ) Если у вас IDE, она должна сразу показать, что что-то пошло не так relaxed
> 
> ![img190420232bda](https://user-images.githubusercontent.com/23196073/233045844-919f656c-8c22-4eff-9859-e7716a761eb4.png)

Да это факт. Я осознаю что программно ничего с этим не сделать т.к. на вход вы просто получите обрезаный пароль без информации о #. Поделился случаем просто.
