### ISSUE TITLE
многосайтовость

### ISSUE THREAD

**Issue by VlMescher** [local-deploy/dl#72]
ни разу не пользовались dl чтобы поднять проект с многосайтовостью, где bitrix, upload, local через симлинки работает.

Подскажите как поднимать такой проект если его структура выглядит примерно так. 
../htdocs/www/

bitrix
upload
local

shop.site.ru/ (root первого сайта)
```
 - bitrix -> ../bitrix
 - upload -> ../upload
 - local -> ../local
```
site.ru/ (root второго сайта)
```
 - bitrix -> ../bitrix
 - upload -> ../upload
 - local -> ../local
```
 
 в конфигах есть DOCUMENT_ROOT, но как сдеалть что-то типа того
 DOCUMENT_ROOT=/var/www/html/site, /var/www/html/shop.site ?

**Comment by varrcan** [comment]
С симлинками вообще нет проблем, такие проекты часто встречаются (например, когда те же директории bitrix, local и тд выносится за пределы докрут).

А вот с многосайтовостью, скорее всего, не получится. По умолчанию образ PHP содержит стандартный конфиг apache, в котором DocumentRoot подменяется на переменную ${DOCUMENT_ROOT}. То есть запустить 2 сайта просто технически невозможно, для этого в конфиге нужно создать второй Virtual Host.

Поэтому одновременно вы можете запустить только 1 версию сайта, либо site.ru, либо shop.site.ru (прописав соответствующий DOCUMENT_ROOT). Чтобы работали 2 одновременно, потребуется переопределить docker-compose php-образа со своей кастомной конфигурацией.

**Comment by varrcan** [comment]
Вы можете полностью заменить образы на свои, единственное условие: нужно прописать labels для траефика, чтобы он подхватил их.

dl работает с docker-compose файлами, там нет никакой магии. Сами файлы расположены в директории:
/home/[user]/.config/dl/config-files/

В зависимости от того, какие параметры вы указали в .env файле, подключается конкретный docker-compose.yaml
То есть, если не указать PHP_VERSION, то docker-compose-apache.yaml (или fpm) у вас просто не запуститься.

Подключить свои yaml файлы можно через переменную APPEND_COMPOSE_FILE, все верно.
Вы можете взять тот же docker-compose-apache.yaml в качестве шаблона и переделать его под себя. В .env файле вы не указываете PHP_VERSION и в APPEND_COMPOSE_FILE пропишите собственный docker-compose.yaml. Но главное, не забудьте про labels, без них не взлетит.
