### ISSUE TITLE
Вопрос

### ISSUE THREAD

**Issue by jasmanchik** [local-deploy/dl#73]
Как-то можно скачивать файлы с сервера командой dl deploy, если в корне проекта нет папки bitrix, но есть _BITRIX?

**Comment by jasmanchik** [comment]
У нас несколько сайтов и у них общее ядро, вынесено за пределы публичной части

**Comment by varrcan** [comment]
Это нормально выносить ядро за пределы докрут, но у вас все равно должен быть симлинк на папку bitrix уровнем выше, правильно?
Если папка называется по другому, можно переопределить загружаемые файлы:

`dl deploy -f -o _BITRIX`

https://local-deploy.github.io/ru/commands#deploy

**Comment by jasmanchik** [comment]
Да все верно, но у меня не получается скачать вашим способом. Ядро битрикс за пределами докрут, и у нее название _BITRIX.
<img width="851" alt="image" src="https://user-images.githubusercontent.com/40543800/234509715-98a3fa63-d97d-453c-b944-cad10087a734.png">

**Comment by jasmanchik** [comment]
Проще переименовать _BITRIX на bitrix или все же можно как-то изловчиться?

**Comment by jasmanchik** [comment]
Хорошо, я понял. Спасибо
