### ISSUE TITLE
Memcache

### ISSUE THREAD

**Issue by jasmanchik** [local-deploy/dl#74]
<img width="794" alt="image" src="https://user-images.githubusercontent.com/40543800/235141077-4f712476-592d-4213-b07c-f52ecf472322.png">

<img width="296" alt="image" src="https://user-images.githubusercontent.com/40543800/235141183-0897a31f-35fe-448d-9f0e-c1a1d0838c65.png">

PHP не видит модуль, хотя я его указал в .env. Хочу использовать для хранения сессий
<img width="514" alt="image" src="https://user-images.githubusercontent.com/40543800/235141422-d8095750-f7a8-424f-82a9-de88ee630993.png">

Не подскажете как можно исправить?

**Comment by varrcan** [comment]
Я проверю, так сразу не скажу. Должно работать из коробки, что называется.

**Comment by jasmanchik** [comment]
Поразбирался немного.
При создании образа php:8.2-apache (возможно и в других также) ставится модуль "memcached", а битрикс проверяет на наличие "memcache". Решил это путем добавления модуля в образ "pecl install memcache"
<img width="426" alt="image" src="https://user-images.githubusercontent.com/40543800/235405534-3ed1ed7a-0f28-46bb-84ec-69922985e6da.png">

Не знаю как у остальных оно работает

**Comment by varrcan** [comment]
Временно можете установить переменную в .env: 
`PHP_IMAGE_VERSION=1.0.2` (для php8.2-apache )
И указать `PHP_MODULES="memcache"`

Но этот образ еще не протестирован толком. Обнаружился баг в **pecl**, на некоторых версиях PHP не ставится `memcached`, но он вам и не нужен. 

Я пока что не буду переключать dl на новый тег, пока не исправят баг (чтобы был доступен и memcache, и memcached), но вы можете его использовать. Образ был почти полностью переписан, сейчас в beta-версии.

**Comment by varrcan** [comment]
В версии [1.0.7](https://github.com/local-deploy/dl/releases/tag/1.0.7) добавлен как memcached, так и memcache.
