### ISSUE TITLE
Директория для конфигов

### ISSUE THREAD

**Issue by jasmanchik** [local-deploy/dl#84]
Поставил заново утилиту, но после первого запуска не появились кфг в директории ~/.config/dl/config-files/. Папки dl просто нет. Что-то поменялось в расположении?

**Comment by varrcan** [comment]
Да, изменилось немного.
Вы удалили старые конфиги перед новой установкой, правильно?
Как ставили новую версию, через скрипт dl_install.sh или через deb файл?

Если через скрипт (бинарник в домашней директории, в .local/bin), то файлы создаются автоматически при первом запуске dl.

Если через deb файл, конфиги копируются из установочного файла в /etc/dl/config-files. А конфигурационный файл config.yaml все также в домашней директории, в .config/dl/

**Comment by jasmanchik** [comment]
Через скрипт ставил. Систему переустанавливал на mac.
У меня нет нигде этих файлов
<img width="421" alt="image" src="https://github.com/local-deploy/dl/assets/40543800/fa020451-5ba1-413b-afdb-8121560eb100">

**Comment by varrcan** [comment]
Вместо статического пути я использовал нативный метод Golang для получения директории конфига текущего пользователя. 
На mac, если не ошибаюсь, это /Library/Application Support в домашней директории пользователя. Проверьте, пожалуйста, скорее всего они там.

Сам dl при этом работает нормально?

**Comment by varrcan** [comment]
Да, действительно, директория конфигов на mac другая.

![img29052023c3ba](https://github.com/local-deploy/dl/assets/23196073/ed93c251-1bf8-4b6d-bcfd-7e78dd9ca8be)

**Comment by jasmanchik** [comment]
> Вместо статического пути я использовал нативный метод Golang для получения директории конфига текущего пользователя. На mac, если не ошибаюсь, это `~/Library/Application Support` в домашней директории пользователя. Проверьте, пожалуйста, скорее всего они там.

Да действительно, лежат тут ~/Library/Application Support. Спасибо.

> Сам dl при этом работает нормально?

Да, все работает
