### ISSUE TITLE
проблемы с обновлением. Раньше все было ок

### ISSUE THREAD

**Issue by VlMescher** [local-deploy/dl#85]
![image](https://github.com/local-deploy/dl/assets/129059800/33f00e40-546c-47dc-a05c-b6570963a80e)

**Comment by varrcan** [comment]
Да, есть такая проблема, обнаружил уже через пару релизов.. С версии 0.* на версию 1.* обновиться не получится штатно, так как изменился формат архива: раньше все файлы были в одном общем архиве, сейчас для каждой ОС и архитектуры отдельный. То есть старые версии при обновлении просто не видят нужных файлов в архиве, так как скачивают первый попавшийся из релиза.

Запустите повторную установку, это решит проблему.

`curl -s https://raw.githubusercontent.com/local-deploy/dl/master/install_dl.sh | bash`

Извините за неудобства, больше так не буду :)

![изображение](https://github.com/local-deploy/dl/assets/23196073/8c2a1de9-8b2f-4c51-9633-abca6e44f3cc)

PS К сожалению, у меня нет никаких каналов уведомлений для таких случаев, кроме документации, может быть стоит создать какой нибудь чат в телеге?

**Comment by varrcan** [comment]
[Проблемы обновления на версию > 1.*](https://github.com/local-deploy/dl/discussions/86)
