### ISSUE TITLE
взаимодействие локальных площадок

### ISSUE THREAD

**Issue by VlMescher** [local-deploy/dl#87]
У меня 2 запущеных проекта. К примеру shop.localhost и crm.localhost

К сожалению запрос с одной площадки на апи соседней не работает. 
Если проверить какой ip резолвится внутри площадки по хосту, то получаем 127.0.0.1

В итоге приходится общаться через nip.io 

Хотел уточнить возможно ли, чтобы и внутри площадок резолвились корректные локальные ip адреса

**Comment by VlMescher** [comment]
Спасибо за развернутый ответ. Собственно это примрно понятно, я хотел уточнить можно ли внутри этой сети резолвить ip для какого-нибудь хоста принудительно.

**Comment by varrcan** [comment]
Если честно, в голову ничего не приходит умного. Потребуется немного переделать базовую архитектуру создания контейнеров, чтобы они запускались в одной сети. При этом контейнеры базы данных должны быть расположены либо в других сетях, либо не со стандартным портом 3306, ибо будут конфликтовать.
Да, порт php тоже будет конфликтовать, из-за того, что общая сеть. Возможно потребуется поставить nginx между traefik и контейнерами php, чтобы по хостам трафик распределял. 

Кажется придется здорово так переписать конфиги docker-compose, это будет очень кастомное решение, от dl останется только traefik разве что.

**Comment by VlMescher** [comment]
итог ясен. Оно того не стоит. Спасибо большое. А ip можно задать принудительно для конейнера? Чтобы не рандомный был

**Comment by varrcan** [comment]
В принципе возможно, но все равно придется переписать конфиги
Как пример https://jtips.dev/naznachaiem-statichieskii-ip-adries-docker-kontieinieru-i-docker-compose/
