### ISSUE TITLE
Реализация команды dl deploy -c

### ISSUE THREAD

**Issue by MrDeff** [local-deploy/dl#89]
Суть, команда скачает конфиг файлы с удаленного сервера и заменит в них данные для подключения к базе на локальные докера.

Для битрикса это файлы
bitrix/.settings.php и bitrix/php_interface/dbconn.php
Для лары 
.envhttps://docs.github.com/github/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax

**Comment by varrcan** [comment]
Здравствуйте, вы можете использовать команду `deploy`, с указанием параметра `-o`.

Как пример
`dl deploy -fo bitrix/.settings.php bitrix/php_interface/dbconn.php`

Для удобства команду можно добавить алиасом bash или отдельной командой через make, например.

**Comment by MrDeff** [comment]
круто, спасибо!
